ChildrenDetails/Models/ChildrenDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrenDetails.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ChildrenDetail
    {
        public int ID { get; set; }

        [Required]
        [DisplayName("Child Last Name")]
        public string Child_Last_Name { get; set; }

        [Required]
        [DisplayName("Child First Name")]
        public string Child_First_Name { get; set; }

        [Required]
        public string Child_Gender { get; set; }

        [Required]
        [DisplayName("Child Birth Date")]
        public System.DateTime Child_Birth_Date { get; set; }

        [Required]
        public int Child_Status { get; set; }

        [Required]
        public string Child_Address { get; set; }

        [Required]
        public int Child_Type { get; set; }

        [Required]
        public string Parent1_Last_Name { get; set; }

        [Required]
        public string Parent1_First_Name { get; set; }

        [Required]
        public string Parent1_Private { get; set; }

        [Required]
        public string Parent1_Gender { get; set; }

        [Required]
        public string Parent1_Child_Relation { get; set; }

        [Required]
        public string Parent1_Address { get; set; }

        [Required]
        public string Parent1_Unit { get; set; }

        [Required]
        public string Parent1_City { get; set; }

        [Required]
        public string Parent1_Province { get; set; }

        [Required]
        public string Parent1_Postal_Code { get; set; }

        [Required]
        public string Parent1_Home_Phone { get; set; }

        [Required]
        public string Parent1_Work_Phone { get; set; }

        [Required]
        public string Parent1_Cell_Phone { get; set; }

        [Required]
        public string Parent1_Email { get; set; }

        [Required]
        public bool Parent1_Primary_Email { get; set; }

        [Required]
        public string Parent1_Comments { get; set; }

        [Required]
        public string Parent1_Special_Custody { get; set; }

        [Required]
        public string Parent2_Last_Name { get; set; }

        [Required]
        public string Parent2_First_Name { get; set; }

        [Required]
        public string Parent2_Private { get; set; }

        [Required]
        public string Parent2_Gender { get; set; }

        [Required]
        public string Parent2_Child_Relation { get; set; }

        [Required]
        public string Parent2_Address { get; set; }

        [Required]
        public string Parent2_Unit { get; set; }

        [Required]
        public string Parent2_City { get; set; }

        [Required]
        public string Parent2_Province { get; set; }

        [Required]
        public string Parent2_Postal_Code { get; set; }

        [Required]
        public string Parent2_Home_Phone { get; set; }

        [Required]
        public string Parent2_Work_Phone { get; set; }

        [Required]
        public string Parent2_Cell_Phone { get; set; }

        [Required]
        public string Parent2_Email { get; set; }

        [Required]
        public bool Parent2_Primary_Email { get; set; }

        [Required]
        public string Parent2_Comments { get; set; }

        [Required]
        public string Parent2_Special_Custody { get; set; }

        [Required]
        public string Sibling_Name { get; set; }

        [Required]
        public int Sibling_Age { get; set; }

        [Required]
        public string Sibling_Gender { get; set; }

        [Required]
        [DisplayName("Contact1 Name")]
        public string Contact1_Name { get; set; }

        [Required]
        [Phone]
        [DisplayName("Contact1 Phone")]
        public string Contact1_Phone { get; set; }

        [Required]
        [EmailAddress]
        [DisplayName("Contact1 Email")]
        public string Contact1_Email { get; set; }

        [Required]
        public string Contact1_Address { get; set; }

        [Required]
        public string Contact1_Relationship { get; set; }

        [Required]
        public string Contact2_Name { get; set; }

        [Required]
        public string Contact2_Phone { get; set; }

        [Required]
        public string Contact2_Email { get; set; }

        [Required]
        public string Contact2_Address { get; set; }

        [Required]
        public string Contact2_Relationship { get; set; }

        [Required]
        public string Contact3_Name { get; set; }

        [Required]
        public string Contact3_Phone { get; set; }

        [Required]
        public string Contact3_Email { get; set; }

        [Required]
        public string Contact3_Address { get; set; }

        [Required]
        public string Contact3_Relationship { get; set; }

        [Required]
        public string Contact4_Name { get; set; }

        [Required]
        public string Contact4_Phone { get; set; }

        [Required]
        public string Contact4_Email { get; set; }

        [Required]
        public string Contact4_Address { get; set; }

        [Required]
        public string Contact4_Relationship { get; set; }

        public List<ChildrenDetail> ChildrenDetails { get; set; }
        public ChildrenDetail SelectedCustomer { get; set; }
        public string DisplayMode { get; set; }
    }
}

ChildrenDetails/Models/ChildrenDetails.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

ChildrenDetails/Controllers/ChildrenDetailsController.cs
using ChildrenDetails.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static ChildrenDetails.Models.ChildrenDetail;

namespace ChildrenDetails.Controllers
{
    public class ChildrenDetailsController : Controller
    {
        // GET: ChildrenDetails
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Save all the Children Details in Database if record is newely created and Update the children details in database if that records is already exist
        /// </summary>
        /// <param name="objChildrenDetail"></param>
        /// <returns></returns>

        [HttpPost]
        public ActionResult Index(ChildrenDetail objChildrenDetail)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ChildrenDetailsEntities db = new ChildrenDetailsEntities();

                    if (TempData["ID"] != null)
                    {
                        int ID = Convert.ToInt32(TempData["ID"]);
                        ChildrenDetail objChildrenDetails = db.ChildrenDetails.FirstOrDefault(x => x.ID == ID);
                        if (objChildrenDetails != null)
                        {
                            objChildrenDetail.ID = ID;
                            db.ChildrenDetails.AddOrUpdate(objChildrenDetail);
                            db.SaveChanges();
                        }
                    }
                    else
                    {
                        db.ChildrenDetails.Add(objChildrenDetail);
                        db.SaveChanges();
                    }
                    ModelState.Clear();
                    return RedirectToAction("Index");
                }

                return View(objChildrenDetail);
            }
            catch (Exception)
            {

                throw;
            }
        }

        /// <summary>
        /// This ActionResult is used for populating the data of all Childrens from database and show it on ChildrenLists page and also searched the children details 
        /// based on First Name and Last Name
        /// </summary>
        /// <param name="searchString"></param>
        /// <returns></returns>
        public ActionResult ChildrenLists(string searchString)
        {

            try
            {

                HttpPostedFileBase[] files;
                files = null;
                ViewBag.files = files;

                ChildrenDetailsEntities objChildrenDetailsEntities = new ChildrenDetailsEntities();

                var data = from item in objChildrenDetailsEntities.ChildrenDetails
                           //orderby item.ID
                           select item;

                if (!String.IsNullOrEmpty(searchString))
                {
                    data = data.Where(s => s.Child_Last_Name.ToUpper().Contains(searchString.ToUpper())
                                           || s.Child_First_Name.ToUpper().Contains(searchString.ToUpper()));
                }

                return View(data.ToList());
            }
            catch (Exception)
            {
                throw;
            }
        }

        /// <summary>
        /// Select existing records of children from ChildrenList page to Update in database
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            try
            {
                using (ChildrenDetailsEntities db = new ChildrenDetailsEntities())
                {
                    ChildrenDetail model = new ChildrenDetail();
                    model.SelectedCustomer = db.ChildrenDetails.Find(id);
                    model.DisplayMode = "ReadOnly";
                    TempData["ID"] = id;
                    return View("Index", model.SelectedCustomer);
                }
            }
            catch (Exception)
            {

                throw;
            }
        }

        /// <summary>
        /// Delete existing records of childredn from ChildrenList page and from database as well
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        
        public ActionResult Delete(int id)
        {
            try
            {
                ChildrenDetailsEntities db = new ChildrenDetailsEntities();
                ChildrenDetail objChildrenDetail = db.ChildrenDetails.Find(id);
                db.ChildrenDetails.Remove(objChildrenDetail);
                db.SaveChanges();
                return RedirectToAction("ChildrenLists");
            }
            catch (Exception)
            {

                throw;
            }
        }

        public ActionResult UploadFiles()
        {
            HttpPostedFileBase[] files;
            files = null;
            ViewBag.files = files;

            return View();
        }

        /// <summary>
        /// Upload Childrens files on local directory folder
        /// </summary>
        /// <param name="files"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UploadFiles(HttpPostedFileBase[] files)
        {

            try
            {
                ChildrenDetailsEntities db = new ChildrenDetailsEntities();

                //if (files != null)
                //{
                //    //Ensure model state is valid  
                //    if (ModelState.IsValid)
                //    {   //iterating through multiple file collection   
                //        foreach (HttpPostedFileBase file in files)
                //        {
                //            //Checking file is available to save.  
                //            if (file != null)
                //            {
                //                var InputFileName = Path.GetFileName(file.FileName);
                //                var ServerSavePath = Path.Combine(Server.MapPath("~/UploadedFiles/") + InputFileName);
                //                //Save file to server folder  
                //                file.SaveAs(ServerSavePath);
                //                //assigning file uploaded status to ViewBag for showing message to user.  
                //                ViewBag.UploadStatus = files.Count().ToString() + " files uploaded successfully.";
                //            }

                //        }
                //    }
                //}

                if (files != null)
                {
                    foreach (var file in files)
                    {
                        // extract only the filename
                        var fileName = Path.GetFileName(file.FileName);

                        // extract the file content to byte array
                        var content = new byte[file.ContentLength];
                        // reads the content from stream
                        file.InputStream.Read(content, 0, file.ContentLength);

                        //get file extesion
                        var fileExtension = Path.GetExtension(fileName);
                        //save file name as uniqe
                        var uniqueFileName = Guid.NewGuid().ToString();

                        ChildrenFileUpload objChildrenFileUpload = new ChildrenFileUpload
                        {
                            File_Name = uniqueFileName,
                            Upload_Date = DateTime.Now,
                            File_Content = content
                        };

                        db.ChildrenFileUploads.Add(objChildrenFileUpload);
                        db.SaveChanges();
                    } 
                }

                return RedirectToAction("ChildrenLists");
            }
            catch (Exception)
            {

                throw;
            }
        }

    }
}

ChildrenDetails/Views/ChildrenDetails/ChildrenLists.cshtml
@model IEnumerable<ChildrenDetails.Models.ChildrenDetail>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ChildrenLists</title>
</head>
<body>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/scripts/jquery-1.12.4.min.js"></script>
    <script src="~/scripts/jquery-ui-1.12.1.min.js"></script>


    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>  


    <script type="text/javascript">
        $(function () { $("#tabs").tabs(); });
    </script>

    <div id="tabs">

        <ul>
            <li><a href="#tabs-1">Children Lists</a></li>
            <li><a href="#tabs-2">Children Files</a></li>
        </ul>

        <div id="tabs-1">
            @using (Html.BeginForm())
            {
                <div id="tabs-1">

                    <h2>Children Datils Lists</h2>
                    <hr />

                    <p>
                        Find by Child First or Last Name: @Html.TextBox("SearchString")
                        <input type="submit" value="Search" />
                    </p>

                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Child_First_Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Child_Last_Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Child_Birth_Date)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Contact1_Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Contact1_Phone)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Contact1_Email)
                            </th>
                            <th></th>
                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Child_First_Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Child_Last_Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Child_Birth_Date)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Contact1_Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Contact1_Phone)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Contact1_Email)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                                </td>
                            </tr>
                        }
                    </table>

                </div>
            }
        </div>

        <div id="tabs-2">
            @using (Html.BeginForm("UploadFiles", "ChildrenDetails", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                @Html.Label("Childrens Files Upload", htmlAttributes: new { @class = "control-label col-md-2" })

                <input type="file" name="files" multiple />
                <input type="submit" value="Upload" />
                
            }
            
        </div>
    </div>
</body>
</html>